### ISSUE TITLE
Staging

### ISSUE THREAD

**Issue by simonmaris** [burglabs/xlab-docs#13]
I was trying to setup a quick staging environment, where on every pull request it automatically spins up a version of the docs including those changes. 

Since it's so easy to serve locally, I'm not sure how relevant this is. 

Anyway, it wasn't as easy as I thought. A possible, and maybe the cleanest, solution would be to: 

1) create a secondary repo, i.e. xlab-docs-staging, also served via gh-pages
2) automatically create a folder in that repository for every pull request (and remove on merge / close)
3) auto post the deployment link in the corresponding section in the pull request. 

If that is something we want, we can set this up in the future. For now, I have disabled the workflow. 

Any thoughts, @alexabruck?

**Comment by alexabruck** [comment]
What would be the need for a staging env? To see the changes without pulling & local setup?

**Comment by simonmaris** [comment]
I might have gotten carried away while setting up actions;)

**Comment by alexabruck** [comment]
I mean there's a lot to explore in the world of automated tests as well (snapshot testing, unit testing, end to end..) - but definitely overkill for this project :-)

**Comment by simonmaris** [comment]
Nooo, we need all of it.
